resolver: lts-11.13

flags: {}
packages:
- ./adiff
- ./adiff-docker
- ./adiff-server
- location: ./language-c-extensible
  extra-dep: true

extra-deps:
- pptable-0.3.0.0
- process-1.6.3.0
- rio-0.1.0.0
- wai-middleware-static-embedded-0.1.0.0

# We need at least sqlite 2.3.24
- git: https://github.com/IreneKnapp/direct-sqlite.git
  commit: 8e3da41c46b5de19942cc7bf421c3deb5117ba7a

#docker:
#   enable: true
#   image: adiff/build
#   set-user: false
