flags: {}
packages:
- .
- ./language-c-extensible
extra-deps:
- rio-0.1.0.0
- suspend-0.2.0.0
- timers-0.2.0.3
- typed-process-0.2.2.0
- unliftio-0.2.6.0

resolver: lts-11.1

# docker:
#   enable: true
#   image: "vdiff:latest"
